;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	helm-M-x
	helm-confirm-and-exit-minibuffer
	org-beginning-of-line
	org-end-of-line
	org-fill-paragraph
	org-insert-todo-heading
	org-kill-line
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	handle-switch-frame
	mouse-buffer-menu
	mouse-set-region
	nov-goto-toc
	org-cycle
	org-cycle-agenda-files
	org-forward-paragraph
	org-open-at-mouse
	org-self-insert-command
	org-shiftcontrolright
	org-todo
	pdf-view-mouse-set-region
	pdf-view-scroll-up-or-next-page
	))
