((magit-commit nil)
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-remote\.<remote>\.*url "https://github.com/tiktaaliki/emacs.git" "git@github.com:tiktaaliki/emacs")
 (magit-revert
  ("--edit"))
 (pomm-transient nil))
